# Generated by Django 5.1.4 on 2024-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_content', models.TextField()),
                ('long_content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('auther_name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
